#!/bin/bash
# krzysckh (c) - under wtfpl 2021

vol=$("$HOME"/scripts/popup/vol | sed 's/%//' | sed 's/on//' | sed 's/ //' | sed 's/.$//')
# replace $HOME/scripts/popup/vol with path to z3bra's ALSA volume script
# http://blog.z3bra.org/2014/04/pop-it-up.html
(
echo -ne "%{F#dedede}"
printf " " && for i in $(seq $vol)
do
	printf "─"
	if [[ $i -gt 8 ]]
	then
		echo -ne "%{F#f04d4d}"
	fi
done

sleep 1
) | lemonbar \
	-g "110x30+20+20" \
	-f "CozetteVector" \
	-B "#222222" \
	-F "#dedede" \
	-U "#dedede" \
	-d
