#!/bin/bash
# shows currenly playing spotify song.
# should be run using 'spt_popup' script
# which also spawns another urxvt window

# dependencies:
# - clr
# - spotify-now
# - spotify client

[ ! -z "$(pgrep bspwm)" ] && bspc node -t floating

tput civis
clr -s "→ " "#a451ee" -O | tr -d '\n'
spotify-now -i "%artist: %title" | tr -d '\n'
read -n 1 -s -r
