#!/bin/bash

export PATH=$PATH:/home/krzych/bin/:/home/krzych/.local/bin/

BSPWM_CONF_DIR="$HOME/.config/bspwm"
PICOM_CONFIG="$HOME/.config/picom/picom.conf"

#=====================================#

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config focused_border_color "#dedede"
bspc config active_border_color "#cccccc"
bspc config normal_border_color "#a451ee"

bspc rule -a state=floating follow=on
bspc rule -a mpv state=pseudo_tiled
bspc rule -a Sxiv state=pseudo_tiled
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr

setxkbmap pl

dunst &

xrdb ~/.Xresources

gwall "#222" "#111" 5

pidof picom && killall -9 picom
picom --config "$PICOM_CONFIG" -b

xbanish &

#pulseaudio -D

#pactl set-default-sink alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo-output

# cd $HOME/.config/luastatus/bspwm && luastatus-stdout-wrapper -B separator="  " title.lua lang.lua clock.lua bspwm2.lua alsa.lua | lemonbar -f"CozetteVector:pixelsize=13, Noto Color Emoji:pixelsize=13, symbola:pixelsize=13" -B"#222222" -p

# status_inf | lemonbar -f"CozetteVector:pixelsize=13, Noto Color Emoji:pixelsize=13, symbola:pixelsize=13" -B"#222222" -p

bspwmbar &

